
// ********RoostGPT********
/*
Test generated by RoostGPT for test constructor_maven using AI Type Open AI and AI Model gpt-4o

ROOST_METHOD_HASH=toString_49373ce4fb
ROOST_METHOD_SIG_HASH=toString_ceffa8036e


Scenario 1: Verify toString returns formatted string for valid input

Details:
  TestName: verifyToStringReturnsFormattedStringForValidInput
  Description: This test checks if the toString method returns a correctly formatted string when the Student object is initialized with valid id, name, and age values.
Execution:
  Arrange: Create a Student object with id=1, name="John Doe", and age=20.
  Act: Call the toString method on the Student object.
  Assert: Use JUnit assertions to verify that the returned string is "ID: 1, Name: John Doe, Age: 20".
Validation:
  This assertion verifies that the toString method correctly formats and returns the string representation of the Student object. It ensures that all fields are included and properly concatenated in the output.

*/

// ********RoostGPT********

package com.example.model;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Tag;
import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.*;

public class StudentToStringTest {

	@Test
	@Tag("valid")
	public void verifyToStringReturnsFormattedStringForValidInput() {
		// Arrange
		Student student = new Student(1, "John Doe", 20);
		// Act
		String result = student.toString();
		// Assert
		assertEquals("ID: 1, Name: John Doe, Age: 20", result);
	}

}